// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CatalogInfoVo struct {
	Id          int64  `json:"id"`
	CatalogName string `json:"catalogName"`
	Level       int32  `json:"level"`
	ParentId    int64  `json:"parentId"`
	Type        int32  `json:"type"`
}

type CatalogListByFileResp struct {
	Catalogs []*CatalogInfoVo `json:"catalogs"`
	Files    []*FileCountVo   `json:"files"`
}

type CatalogResp struct {
	Id           int64          `json:"id"`
	CatalogName  string         `json:"catalogName"`
	Description  string         `json:"description,omitempty"`
	Level        int32          `json:"level"`
	ParentId     int64          `json:"parentId"`
	Type         int32          `json:"type"`
	Children     []*CatalogResp `json:"children,omitempty"`
	Count        int32          `json:"count,omitempty"`
	HaveChildren bool           `json:"haveChildren"`
}

type CreateCatalogReq struct {
	CatalogName string `json:"catalogName" validate:"required"`
	ParentId    int64  `json:"parentId" validate:"required"`
	Type        int32  `json:"type" validate:"required,min=1,max=4"`
	Description string `json:"description,optional" validate:"max=300"`
}

type QueryReq struct {
	Type    int32  `form:"type" validate:"required,min=1,max=4"`
	Keyword string `form:"keyword,optional"`
}

type QueryTreeReq struct {
	Type int32 `form:"type,optional" validate:"omitempty,min=1,max=4"`
	Id   int64 `form:"id,optional"`
}

type QueryWithFileReq struct {
	Keyword string `form:"keyword,optional"`
}

type UpdateCatalogReq struct {
	CatalogName string `json:"catalogName" validate:"required,max=20"`
	Description string `json:"description,optional" validate:"max=300"`
}
