// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateReq struct {
	CatalogName string `json:"catalogName,required,max=20"`  // 目录名称（1-20字符）
	ParentId    string `json:"parentId,required"`            // 父目录ID
	Description string `json:"description,optional,max=255"` // 目录说明（可选）
}

type CreateResp struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

type DeleteReq struct {
	Id string `path:"id,required"` // 目录ID（路径参数）
}

type DeleteResp struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

type QueryReq struct {
	Type        int32   `form:"type,required"`         // 目录类型
	CatalogName *string `form:"catalog_name,optional"` // 目录名称（模糊查询）
}

type QueryResp struct {
	Code        string           `json:"code"`
	Description string           `json:"description"`
	Data        []*CatalogInfoVo `json:"data,omitempty"`
}

type QueryTreeReq struct {
	Type int32  `form:"type,required"` // 目录类型 1=数据元, 2=码表, 3=编码规则, 4=文件
	Id   *int64 `form:"id,optional"`   // 目录ID（可选，指定时返回该节点子树）
}

type QueryTreeResp struct {
	Code        string             `json:"code"`
	Description string             `json:"description"`
	Data        *CatalogTreeNodeVo `json:"data,omitempty"`
}

type QueryWithFileReq struct {
	CatalogName *string `form:"catalog_name,optional"` // 目录名称（模糊查询）
}

type QueryWithFileResp struct {
	Code        string               `json:"code"`
	Description string               `json:"description"`
	Data        *CatalogListByFileVo `json:"data,omitempty"`
}

type UpdateReq struct {
	Id          string `path:"id,required"`                  // 目录ID（路径参数）
	CatalogName string `json:"catalogName,required,max=20"`  // 目录名称
	ParentId    string `json:"parentId,required"`            // 父目录ID
	Description string `json:"description,optional,max=255"` // 目录说明（可选）
}

type UpdateResp struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}
