// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateDataElementReq struct {
	NameEn        string  `json:"nameEn,optional" validate:"required"`
	NameCn        string  `json:"nameCn,optional" validate:"required"`
	Synonym       string  `json:"synonym,optional"`
	StdType       int32   `json:"stdType,optional" validate:"required"`
	DataType      int32   `json:"dataType,optional" validate:"required"`
	DataLength    int32   `json:"dataLength,optional"`
	DataPrecision int32   `json:"dataPrecision,optional"`
	DictCode      string  `json:"dictCode,optional"`
	RuleId        int64   `json:"ruleId,optional"`
	RelationType  string  `json:"relationType,optional" validate:"required"`
	CatalogId     int64   `json:"catalogId,optional" validate:"required"`
	LabelId       int64   `json:"labelId,optional"`
	Description   string  `json:"description,optional"`
	DepartmentIds string  `json:"departmentIds,optional"`
	ThirdDeptId   string  `json:"thirdDeptId,optional"`
	StdFiles      []int64 `json:"stdFiles,optional"`
}

type DataElementDetailReq struct {
	Type  int32 `form:"type,optional" validate:"required"` // 1=按ID查询, 2=按Code查询
	Value int64 `form:"value,optional" validate:"required"`
}

type DataElementDetailVo struct {
	Id             int64       `json:"id"`
	Code           int64       `json:"code"`
	NameEn         string      `json:"nameEn"`
	NameCn         string      `json:"nameCn"`
	Synonym        string      `json:"synonym"`
	StdType        int32       `json:"stdType"`
	DataType       int32       `json:"dataType"`
	DataLength     int32       `json:"dataLength"`
	DataPrecision  int32       `json:"dataPrecision"`
	DictCode       string      `json:"dictCode"`
	RuleId         int64       `json:"ruleId"`
	RelationType   string      `json:"relationType"`
	CatalogId      int64       `json:"catalogId"`
	LabelId        int64       `json:"labelId"`
	Description    string      `json:"description"`
	Version        int32       `json:"version"`
	State          string      `json:"state"`
	DepartmentIds  string      `json:"departmentIds"`
	ThirdDeptId    string      `json:"thirdDeptId"`
	DisableReason  string      `json:"disableReason"`
	CreateUser     string      `json:"createUser"`
	CreateTime     string      `json:"createTime"`
	UpdateTime     string      `json:"updateTime"`
	CatalogName    string      `json:"catalogName"`
	DepartmentPath string      `json:"departmentPath"`
	ValueRange     string      `json:"valueRange"`
	DictName       string      `json:"dictName"`
	RuleName       string      `json:"ruleName"`
	StdFiles       []StdFileVo `json:"stdFiles"`
}

type DataElementListReq struct {
	Offset        int32  `form:"offset,default=1,range=[1:]"`
	Limit         int32  `form:"limit,default=10,range=[0:2000]"`
	Direction     string `form:"direction,default=desc,options=asc|desc"`
	Sort          string `form:"sort,default=created_at,options=created_at|updated_at"`
	Keyword       string `form:"keyword,optional"`
	CatalogId     int64  `form:"catalogId,optional"`
	State         string `form:"state,optional,options=enable|disable"`
	StdType       int32  `form:"stdType,optional"`
	DataType      int32  `form:"dataType,optional"`
	RelationType  string `form:"relationType,optional,options=no|codeTable|codeRule"`
	DepartmentIds string `form:"departmentIds,optional"`
}

type DataElementListVo struct {
	TotalCount int64           `json:"totalCount"`
	Entries    []DataElementVo `json:"entries"`
}

type DataElementQueryByFileCatalogReq struct {
	Offset    int32  `form:"offset,default=1,range=[1:]"`
	Limit     int32  `form:"limit,default=10,range=[0:2000]"`
	Direction string `form:"direction,default=desc,options=asc|desc"`
	Sort      string `form:"sort,default=created_at,options=created_at|updated_at"`
	CatalogId int64  `form:"catalogId,optional" validate:"required"` // -1表示未关联文件的数据元
}

type ExportDataElementReq struct {
	CatalogId int64   `json:"catalogId,optional"`
	State     string  `json:"state,optional,options=enable|disable"`
	Ids       []int64 `json:"ids,optional"`
}

type ExportVo struct {
	DownloadUrl string `json:"downloadUrl"`
	FileName    string `json:"fileName"`
}

type GetPageByRuleIdReq struct {
	RuleId int64 `json:"ruleId,optional" validate:"required"`
	Offset int32 `json:"offset,optional,default=1"`
	Limit  int32 `json:"limit,optional,default=10"`
}

type ImportDataElementReq struct {
	CatalogId int64 `form:"catalogId,optional" validate:"required"`
}

type ImportResultVo struct {
	SuccessCount int32               `json:"successCount"`
	FailCount    int32               `json:"failCount"`
	Errors       []ImportErrorItemVo `json:"errors"`
}

type IsRepeatReq struct {
	NameCn  string `form:"nameCn,optional"`
	NameEn  string `form:"nameEn,optional"`
	StdType int32  `form:"stdType,optional"`
	Id      int64  `form:"id,optional"` // 排除的数据元ID（用于修改时排除自身）
}

type IsRepeatVo struct {
	Result bool `json:"result"`
}

type QueryByStdFileReq struct {
	Offset    int32  `form:"offset,default=1,range=[1:]"`
	Limit     int32  `form:"limit,default=10,range=[0:2000]"`
	Direction string `form:"direction,default=desc,options=asc|desc"`
	Sort      string `form:"sort,default=created_at,options=created_at|updated_at"`
	StdFileId int64  `form:"stdFileId,optional" validate:"required"`
}

type QueryStdFilePageReq struct {
	Offset    int32  `form:"offset,default=1,range=[1:]"`
	Limit     int32  `form:"limit,default=10,range=[0:2000]"`
	Direction string `form:"direction,default=desc,options=asc|desc"`
	Sort      string `form:"sort,default=created_at,options=created_at|updated_at"`
}

type StdFileListVo struct {
	TotalCount int64       `json:"totalCount"`
	Entries    []StdFileVo `json:"entries"`
}

type UpdateDataElementReq struct {
	Id            int64   `json:"id,optional" validate:"required"`
	NameEn        string  `json:"nameEn,optional"`
	NameCn        string  `json:"nameCn,optional"`
	Synonym       string  `json:"synonym,optional"`
	StdType       int32   `json:"stdType,optional"`
	DataType      int32   `json:"dataType,optional"`
	DataLength    int32   `json:"dataLength,optional"`
	DataPrecision int32   `json:"dataPrecision,optional"`
	DictCode      string  `json:"dictCode,optional"`
	RuleId        int64   `json:"ruleId,optional"`
	RelationType  string  `json:"relationType,optional"`
	CatalogId     int64   `json:"catalogId,optional"`
	LabelId       int64   `json:"labelId,optional"`
	Description   string  `json:"description,optional"`
	DepartmentIds string  `json:"departmentIds,optional"`
	ThirdDeptId   string  `json:"thirdDeptId,optional"`
	StdFiles      []int64 `json:"stdFiles,optional"`
}

type UpdateStateReq struct {
	State  string `json:"state,optional" validate:"required,options=enable|disable"`
	Reason string `json:"reason,optional"`
}
