// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddDictRelationReq struct {
	StdFiles []int64 `json:"stdFiles,optional"`
}

type CreateDictReq struct {
	ChName        string       `json:"chName"`
	EnName        string       `json:"enName"`
	Description   string       `json:"description,optional"`
	OrgType       int32        `json:"orgType"`
	CatalogId     int64        `json:"catalogId"`
	Enums         []DictEnumVo `json:"enums"`
	StdFiles      []int64      `json:"stdFiles,optional"`
	DepartmentIds string       `json:"departmentIds,optional"`
}

type DictBaseResp struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

type DictDataElementDataListResp struct {
	Data       []interface{} `json:"data"`
	TotalCount int64         `json:"totalCount"`
}

type DictDataListResp struct {
	Data       []DictVo `json:"data"`
	TotalCount int64    `json:"totalCount"`
}

type DictEnumDataListResp struct {
	Data       []DictEnumVo `json:"data"`
	TotalCount int64        `json:"totalCount"`
}

type DictEnumGetListReq struct {
	DictId int64 `form:"dict_id"`
}

type DictEnumListQuery struct {
	DictId  int64  `form:"dict_id"`
	Keyword string `form:"keyword,optional"`
	Offset  int    `form:"offset,default=1,range=[1:]"`
	Limit   int    `form:"limit,default=10,range=[0:2000]"`
}

type DictEnumVo struct {
	Id    int64  `json:"id,optional"`
	Code  string `json:"code"`
	Value string `json:"value"`
}

type DictListQuery struct {
	Keyword      string `form:"keyword,optional"`
	CatalogId    int64  `form:"catalogId,optional"`
	OrgType      int32  `form:"orgType,optional"`
	State        string `form:"state,optional,options=enable|disable"`
	DepartmentId string `form:"department_id,optional"`
	Offset       int    `form:"offset,default=1,range=[1:]"`
	Limit        int    `form:"limit,default=10,range=[0:2000]"`
	Sort         string `form:"sort,default=update_time,options=update_time|create_time"`
	Direction    string `form:"direction,default=desc,options=asc|desc"`
}

type DictStdFileDataListResp struct {
	Data       []interface{} `json:"data"`
	TotalCount int64         `json:"totalCount"`
}

type DictVo struct {
	Id                  int64        `json:"id"`
	Code                int64        `json:"code"`
	ChName              string       `json:"chName"`
	EnName              string       `json:"enName"`
	Description         string       `json:"description"`
	OrgType             int32        `json:"orgType"`
	Version             int32        `json:"version"`
	State               string       `json:"state"`
	UsedFlag            bool         `json:"usedFlag"`
	CatalogId           int64        `json:"catalogId"`
	CatalogName         string       `json:"catalogName"`
	Enums               []DictEnumVo `json:"enums"`
	DepartmentId        string       `json:"departmentId"`
	DepartmentName      string       `json:"departmentName"`
	DepartmentPathNames string       `json:"departmentPathNames"`
	CreateTime          string       `json:"createTime"`
	CreateUser          string       `json:"createUser"`
	UpdateTime          string       `json:"updateTime"`
	UpdateUser          string       `json:"updateUser"`
}

type QueryDictByStdFileCatalogReq struct {
	CatalogId int64  `form:"catalog_id,optional"`
	Keyword   string `form:"keyword,optional"`
	OrgType   int32  `form:"org_type,optional"`
	State     string `form:"state,optional,options=enable|disable"`
	Offset    int    `form:"offset,default=1,range=[1:]"`
	Limit     int    `form:"limit,default=10,range=[0:2000]"`
}

type QueryDictByStdFileReq struct {
	FileId       int64  `form:"file_id,optional"`
	Keyword      string `form:"keyword,optional"`
	OrgType      int32  `form:"org_type,optional"`
	State        string `form:"state,optional,options=enable|disable"`
	DepartmentId string `form:"department_id,optional"`
	Offset       int    `form:"offset,default=1,range=[1:]"`
	Limit        int    `form:"limit,default=10,range=[0:2000]"`
}

type QueryDictDataExistsReq struct {
	FilterId      int64  `form:"filter_id,optional"`
	OrgType       int32  `form:"org_type"`
	ChName        string `form:"ch_name,optional"`
	EnName        string `form:"en_name,optional"`
	DepartmentIds string `form:"departmentIds,optional"`
}

type UpdateDictReq struct {
	ChName        string       `json:"chName"`
	EnName        string       `json:"enName"`
	Description   string       `json:"description,optional"`
	OrgType       int32        `json:"orgType"`
	CatalogId     int64        `json:"catalogId"`
	Enums         []DictEnumVo `json:"enums"`
	StdFiles      []int64      `json:"stdFiles,optional"`
	DepartmentIds string       `json:"departmentIds,optional"`
}

type UpdateDictStateReq struct {
	State  string `json:"state,options=enable|disable"`
	Reason string `json:"reason,optional"`
}
