// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateRuleReq struct {
	Name          string       `json:"name"`
	CatalogId     int64        `json:"catalogId"`
	OrgType       int32        `json:"orgType"`
	Description   string       `json:"description,optional"`
	RuleType      string       `json:"ruleType"`
	Regex         string       `json:"regex,optional"`
	Custom        []RuleCustom `json:"custom,optional"`
	StdFileIds    []int64      `json:"stdFileIds,optional"`
	DepartmentIds string       `json:"departmentIds,optional"`
}

type EmptyResp struct {
}

type RemoveCatalogReq struct {
	Ids       []int64 `json:"ids"`
	CatalogId int64   `json:"catalogId"`
}

type RuleListQuery struct {
	Keyword   string `form:"keyword,optional"`
	CatalogId int64  `form:"catalogId,optional"`
	OrgType   int32  `form:"orgType,optional,default=-1"`
	State     int32  `form:"state,optional,default=-1"`
	RuleType  string `form:"ruleType,optional"`
	Offset    int    `form:"offset,default=1,range=[1:]"`
	Limit     int    `form:"limit,default=10,range=[0:2000]"`
}

type RuleListResp struct {
	Entries    []RuleResp `json:"entries"`
	TotalCount int64      `json:"total_count"`
}

type RuleResp struct {
	Id            int64   `json:"id"`
	Name          string  `json:"name"`
	CatalogId     int64   `json:"catalogId"`
	CatalogName   string  `json:"catalogName"`
	OrgType       int32   `json:"orgType"`
	Description   string  `json:"description"`
	RuleType      string  `json:"ruleType"`
	Version       int32   `json:"version"`
	Expression    string  `json:"expression"`
	State         int32   `json:"state"`
	DisableReason string  `json:"disableReason"`
	AuthorityId   string  `json:"authorityId"`
	DepartmentIds string  `json:"departmentIds"`
	ThirdDeptId   string  `json:"thirdDeptId"`
	CreateTime    string  `json:"createTime"`
	CreateUser    string  `json:"createUser"`
	UpdateTime    string  `json:"updateTime"`
	UpdateUser    string  `json:"updateUser"`
	StdFileIds    []int64 `json:"stdFileIds"`
	Used          bool    `json:"used"`
}

type UpdateRuleReq struct {
	Name          string       `json:"name"`
	CatalogId     int64        `json:"catalogId"`
	OrgType       int32        `json:"orgType"`
	Description   string       `json:"description,optional"`
	RuleType      string       `json:"ruleType"`
	Regex         string       `json:"regex,optional"`
	Custom        []RuleCustom `json:"custom,optional"`
	StdFileIds    []int64      `json:"stdFileIds,optional"`
	DepartmentIds string       `json:"departmentIds,optional"`
}

type UpdateRuleStateReq struct {
	State  string `json:"state"`
	Reason string `json:"reason,optional"`
}
