// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResp struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

type BatchStateReq struct {
	Ids    []int64 `json:"ids,optional" validate:"required"`
	State  string  `json:"state,optional" validate:"required,oneof=enable disable"`
	Reason string  `json:"reason,optional"`
}

type CreateStdFileReq struct {
	Number         string `form:"number,optional"`
	Name           string `form:"name,optional" validate:"required,max=300"`
	CatalogId      int64  `form:"catalog_id,optional,default=44"`
	OrgType        int32  `form:"org_type,optional" validate:"required"`
	ActDate        string `form:"act_date,optional"`
	PublishDate    string `form:"publish_date,optional"`
	Description    string `form:"description,optional" validate:"max=300"`
	AttachmentType string `form:"attachment_type,optional" validate:"required,oneof=FILE URL"`
	AttachmentUrl  string `form:"attachment_url,optional"`
	State          string `form:"state,optional" validate:"omitempty,oneof=enable disable"`
	DepartmentIds  string `form:"department_ids,optional"`
}

type StdFileDataListResp struct {
	TotalCount int64               `json:"totalCount"`
	Data       []StdFileDetailResp `json:"data"`
}

type StdFileDetailResp struct {
	Id                  int64  `json:"id"`
	Number              string `json:"number"`
	Name                string `json:"name"`
	CatalogId           int64  `json:"catalogId"`
	CatalogName         string `json:"catalogName,omitempty"`
	ActDate             string `json:"actDate,omitempty"`
	PublishDate         string `json:"publishDate,omitempty"`
	DisableDate         string `json:"disableDate,omitempty"`
	AttachmentType      string `json:"attachmentType"`
	AttachmentUrl       string `json:"attachmentUrl,omitempty"`
	FileName            string `json:"fileName,omitempty"`
	OrgType             int32  `json:"orgType"`
	Description         string `json:"description,omitempty"`
	State               string `json:"state"`
	DisableReason       string `json:"disableReason,omitempty"`
	Version             int    `json:"version"`
	DepartmentId        string `json:"departmentId,omitempty"`
	DepartmentName      string `json:"departmentName,omitempty"`
	DepartmentPathNames string `json:"departmentPathNames,omitempty"`
	CreateTime          string `json:"createTime,omitempty"`
	CreateUser          string `json:"createUser,omitempty"`
	UpdateTime          string `json:"updateTime,omitempty"`
	UpdateUser          string `json:"updateUser,omitempty"`
}

type StdFileListQuery struct {
	CatalogId    int64  `form:"catalog_id,optional"`
	Keyword      string `form:"keyword,optional"`
	OrgType      int32  `form:"org_type,optional"`
	State        string `form:"state,optional" validate:"omitempty,oneof=enable disable"`
	Offset       int    `form:"offset,optional,default=1"`
	Limit        int    `form:"limit,optional,default=20"`
	Sort         string `form:"sort,optional,default=update_time"`
	Direction    string `form:"direction,optional,default=desc"`
	DepartmentId string `form:"department_id,optional"`
}

type StdFileRelationDto struct {
	DeIds   []int64 `json:"deIds,optional"`
	DictIds []int64 `json:"dictIds,optional"`
	RuleIds []int64 `json:"ruleIds,optional"`
}

type StdFileRelationQuery struct {
	Offset int `form:"offset,optional,default=1"`
	Limit  int `form:"limit,optional,default=20"`
}

type StdFileRelationResp struct {
	DeIds   []int64 `json:"deIds"`
	DictIds []int64 `json:"dictIds"`
	RuleIds []int64 `json:"ruleIds"`
}

type UpdateStdFileReq struct {
	Id             int64  `path:"id"`
	Number         string `form:"number,optional"`
	Name           string `form:"name,optional" validate:"required,max=300"`
	CatalogId      int64  `form:"catalog_id,optional" validate:"required"`
	OrgType        int32  `form:"org_type,optional" validate:"required"`
	ActDate        string `form:"act_date,optional"`
	PublishDate    string `form:"publish_date,optional"`
	Description    string `form:"description,optional" validate:"max=300"`
	AttachmentType string `form:"attachment_type,optional" validate:"required,oneof=FILE URL"`
	AttachmentUrl  string `form:"attachment_url,optional"`
	State          string `form:"state,optional" validate:"omitempty,oneof=enable disable"`
	DepartmentIds  string `form:"department_ids,optional"`
}

type UpdateStdFileStateReq struct {
	State  string `json:"state,optional" validate:"required,oneof=enable disable"`
	Reason string `json:"reason,optional"`
}
