// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AcceptReq struct {
	Ids []string `json:"ids,optional" validate:"required"`
}

type AddToPendingReq struct {
	BusinessTable            string `json:"businessTable,optional" validate:"required"`
	BusinessTableDescription string `json:"businessTableDescription,optional"`
	TableField               string `json:"tableField,optional"`
	CreateUserPhone          string `json:"createUserPhone,optional"`
}

type BusinessTableListResp struct {
	TotalCount int64               `json:"totalCount"`
	Data       []BusinessTableResp `json:"data"`
}

type BusinessTableStateListResp struct {
	TotalCount int64                  `json:"totalCount"`
	Data       []BusinessTableStateVo `json:"data"`
}

type CancelFieldReq struct {
	Ids []string `json:"ids,optional" validate:"required"`
}

type CreateTaskReq struct {
	TaskId  string   `json:"taskId,optional" validate:"required"`
	Ids     []string `json:"ids,optional" validate:"required"`
	Webhook string   `json:"webhook,optional"`
}

type FieldListResp struct {
	TotalCount int64       `json:"totalCount"`
	Data       []FieldResp `json:"data"`
}

type PageInfo struct {
	PageBaseInfo
	Direction string `form:"direction,default=desc,options=asc|desc"`               // 排序方向：asc 正序，desc 倒序
	Sort      string `form:"sort,default=created_at,options=created_at|updated_at"` // 排序字段
}

type PageInfoWithKeyword struct {
	PageInfo
	KeywordInfo
}

type ProcessResp struct {
	FinishNumber int `json:"finishNumber"`
	TotalNumber  int `json:"totalNumber"`
}

type RuleRecReq struct {
	BusinessTable         string `json:"businessTable,optional" validate:"required"`
	TableField            string `json:"tableField,optional" validate:"required"`
	TableFieldDescription string `json:"tableFieldDescription,optional"`
	DataType              string `json:"dataType,optional"`
}

type StagingRelationReq struct {
	TaskId        int64       `json:"taskId,optional" validate:"required"`
	BusinessTable string      `json:"businessTable,optional" validate:"required"`
	Fields        []FieldInfo `json:"fields,optional"`
}

type StdRecReq struct {
	TaskId                int64  `json:"taskId,optional" validate:"required"`
	BusinessTable         string `json:"businessTable,optional" validate:"required"`
	TableField            string `json:"tableField,optional" validate:"required"`
	TableFieldDescription string `json:"tableFieldDescription,optional"`
}

type StdRecResp struct {
	Code        string       `json:"code"`
	Description string       `json:"description"`
	Data        []StdRecItem `json:"data"`
}

type SubmitDataElementReq struct {
	Id            string `json:"id,optional" validate:"required"`
	DataElementId string `json:"dataElementId,optional"`
}

type TaskBaseResp struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

type TaskDataListResp struct {
	TotalCount int64      `json:"totalCount"`
	Data       []TaskResp `json:"data"`
}

type TaskDetailResp struct {
	Task    TaskResp              `json:"task"`
	Results []TaskStdCreateResult `json:"results"`
}

type UpdateDescriptionReq struct {
	FieldId          int64  `json:"fieldId,optional" validate:"required"`
	FieldDescription string `json:"fieldDescription,optional"`
}

type UpdateTableNameReq struct {
	TableId   int64  `json:"tableId,optional" validate:"required"`
	TableName string `json:"tableName,optional" validate:"required"`
}
