// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type Catalog struct {
	Id          string `json:"id"`
	CatalogName string `json:"catalogName"`
	Description string `json:"description"`
	Level       int32  `json:"level"`
	ParentId    string `json:"parentId"`
	Type        int32  `json:"type"`
	AuthorityId string `json:"authorityId,omitempty"`
}

type CatalogInfoVo struct {
	Id          string `json:"id"`
	CatalogName string `json:"catalogName"`
	Description string `json:"description"`
	Level       int32  `json:"level"`
	ParentId    string `json:"parentId"`
	Type        int32  `json:"type"`
	AuthorityId string `json:"authorityId,omitempty"`
	Count       int32  `json:"count,omitempty"`
}

type CatalogListByFileVo struct {
	Catalogs []*Catalog     `json:"catalogs"`
	Files    []*FileCountVo `json:"files"`
}

type CatalogTreeNodeVo struct {
	Id           string               `json:"id"`
	CatalogName  string               `json:"catalogName"`
	Description  string               `json:"description"`
	Level        int32                `json:"level"`
	ParentId     string               `json:"parentId"`
	Type         int32                `json:"type"`
	AuthorityId  string               `json:"authorityId,omitempty"`
	Count        int32                `json:"count,omitempty"`
	Children     []*CatalogTreeNodeVo `json:"children,omitempty"`
	HaveChildren bool                 `json:"haveChildren"`
}

type CreateReq struct {
	CatalogName string `json:"catalogName,required,max=20"`  // 目录名称（1-20字符）
	ParentId    string `json:"parentId,required"`            // 父目录ID
	Description string `json:"description,optional,max=255"` // 目录说明（可选）
}

type CreateResp struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

type DeleteReq struct {
	Id string `path:"id,required"` // 目录ID（路径参数）
}

type DeleteResp struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}

type EmptyResp struct {
}

type FileCountVo struct {
	FileId    string `json:"fileId"`
	FileName  string `json:"fileName"`
	CatalogId string `json:"catalogId"`
}

type HealthResp struct {
	Status string `json:"status"`
}

type IdReq struct {
	Id int64 `path:"id"`
}

type IdsReq struct {
	Ids []int64 `json:"ids"`
}

type KeywordInfo struct {
	Keyword string `form:"keyword,optional"` // 关键字查询
}

type PageBaseInfo struct {
	Offset int `form:"offset,default=1,range=[1:]"`     // 页码，默认1
	Limit  int `form:"limit,default=10,range=[0:2000]"` // 每页大小，默认10，0表示不分页
}

type PageInfo struct {
	PageBaseInfo
	Direction string `form:"direction,default=desc,options=asc|desc"`               // 排序方向：asc 正序，desc 倒序
	Sort      string `form:"sort,default=created_at,options=created_at|updated_at"` // 排序字段
}

type PageInfoWithKeyword struct {
	PageInfo
	KeywordInfo
}

type PageResp struct {
	Entries    interface{} `json:"entries"`     // 数据列表
	TotalCount int64       `json:"total_count"` // 总记录数
}

type QueryReq struct {
	Type        int32   `form:"type,required"`         // 目录类型
	CatalogName *string `form:"catalog_name,optional"` // 目录名称（模糊查询）
}

type QueryResp struct {
	Code        string           `json:"code"`
	Description string           `json:"description"`
	Data        []*CatalogInfoVo `json:"data,omitempty"`
}

type QueryTreeReq struct {
	Type int32  `form:"type,required"` // 目录类型 1=数据元, 2=码表, 3=编码规则, 4=文件
	Id   *int64 `form:"id,optional"`   // 目录ID（可选，指定时返回该节点子树）
}

type QueryTreeResp struct {
	Code        string             `json:"code"`
	Description string             `json:"description"`
	Data        *CatalogTreeNodeVo `json:"data,omitempty"`
}

type QueryWithFileReq struct {
	CatalogName *string `form:"catalog_name,optional"` // 目录名称（模糊查询）
}

type QueryWithFileResp struct {
	Code        string               `json:"code"`
	Description string               `json:"description"`
	Data        *CatalogListByFileVo `json:"data,omitempty"`
}

type UpdateReq struct {
	Id          string `path:"id,required"`                  // 目录ID（路径参数）
	CatalogName string `json:"catalogName,required,max=20"`  // 目录名称
	ParentId    string `json:"parentId,required"`            // 父目录ID
	Description string `json:"description,optional,max=255"` // 目录说明（可选）
}

type UpdateResp struct {
	Code        string `json:"code"`
	Description string `json:"description"`
}
