// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type HealthResp struct {
	Status string `json:"status"`
}

type IdReq struct {
	Id int64 `path:"id"`
}

type IdsReq struct {
	Ids []int64 `json:"ids"`
}

type KeywordInfo struct {
	Keyword string `form:"keyword,optional"` // 关键字查询
}

type PageBaseInfo struct {
	Offset int `form:"offset,default=1,range=[1:]"`     // 页码，默认1
	Limit  int `form:"limit,default=10,range=[0:2000]"` // 每页大小，默认10，0表示不分页
}

type PageInfo struct {
	PageBaseInfo
	Direction string `form:"direction,default=desc,options=asc|desc"`               // 排序方向：asc 正序，desc 倒序
	Sort      string `form:"sort,default=created_at,options=created_at|updated_at"` // 排序字段
}

type PageInfoWithKeyword struct {
	PageInfo
	KeywordInfo
}

type PageResp struct {
	Entries    interface{} `json:"entries"`     // 数据列表
	TotalCount int64       `json:"total_count"` // 总记录数
}

type RemoveCatalogReq struct {
	Ids       []int64 `json:"ids"`
	CatalogId int64   `json:"catalogId"`
}

type RuleCustom struct {
	Type          string `json:"type"`
	Value         string `json:"value"`
	SegmentLength int    `json:"segmentLength"`
	Count         int    `json:"count"`
}

type UpdateRuleStateReq struct {
	State  string `json:"state"`
	Reason string `json:"reason,optional"`
}
