// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	catalog "github.com/kweaver-ai/dsg/services/apps/standardization-backend/api/internal/handler/catalog"
	dataelement "github.com/kweaver-ai/dsg/services/apps/standardization-backend/api/internal/handler/dataelement"
	dict "github.com/kweaver-ai/dsg/services/apps/standardization-backend/api/internal/handler/dict"
	rule "github.com/kweaver-ai/dsg/services/apps/standardization-backend/api/internal/handler/rule"
	stdfile "github.com/kweaver-ai/dsg/services/apps/standardization-backend/api/internal/handler/stdfile"
	task "github.com/kweaver-ai/dsg/services/apps/standardization-backend/api/internal/handler/task"
	"github.com/kweaver-ai/dsg/services/apps/standardization-backend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthCheckHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 创建目录
				Method:  http.MethodPost,
				Path:    "/catalog",
				Handler: catalog.CreateCatalogHandler(serverCtx),
			},
			{
				// 修改目录
				Method:  http.MethodPut,
				Path:    "/catalog/:id",
				Handler: catalog.UpdateCatalogHandler(serverCtx),
			},
			{
				// 删除目录
				Method:  http.MethodDelete,
				Path:    "/catalog/:id",
				Handler: catalog.DeleteCatalogHandler(serverCtx),
			},
			{
				// 检索目录
				Method:  http.MethodGet,
				Path:    "/catalog/query",
				Handler: catalog.QueryHandler(serverCtx),
			},
			{
				// 查询目录及文件树
				Method:  http.MethodGet,
				Path:    "/catalog/query/with_file",
				Handler: catalog.QueryWithFileHandler(serverCtx),
			},
			{
				// 查询目录树
				Method:  http.MethodGet,
				Path:    "/catalog/query_tree",
				Handler: catalog.QueryTreeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/standardization/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenCheck},
			[]rest.Route{
				{
					// 创建数据元
					Method:  http.MethodPost,
					Path:    "/",
					Handler: dataelement.CreateDataElementHandler(serverCtx),
				},
				{
					// 分页查询数据元
					Method:  http.MethodGet,
					Path:    "/",
					Handler: dataelement.ListDataElementHandler(serverCtx),
				},
				{
					// 编辑数据元
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: dataelement.UpdateDataElementHandler(serverCtx),
				},
				{
					// 删除数据元
					Method:  http.MethodDelete,
					Path:    "/:ids",
					Handler: dataelement.DeleteDataElementHandler(serverCtx),
				},
				{
					// 批量移动数据元到指定目录
					Method:  http.MethodPost,
					Path:    "/catalog/remove",
					Handler: dataelement.RemoveCatalogHandler(serverCtx),
				},
				{
					// 查看数据元详情
					Method:  http.MethodGet,
					Path:    "/detail",
					Handler: dataelement.GetDataElementDetailHandler(serverCtx),
				},
				{
					// 导出数据元
					Method:  http.MethodPost,
					Path:    "/export",
					Handler: dataelement.ExportDataElementHandler(serverCtx),
				},
				{
					// 批量导入数据元
					Method:  http.MethodPost,
					Path:    "/import",
					Handler: dataelement.ImportDataElementHandler(serverCtx),
				},
				{
					// 删除数据元标签
					Method:  http.MethodDelete,
					Path:    "/label/:id",
					Handler: dataelement.DeleteLabelHandler(serverCtx),
				},
				{
					// 按标准文件查询数据元
					Method:  http.MethodGet,
					Path:    "/query/byStdFile",
					Handler: dataelement.QueryByStdFileHandler(serverCtx),
				},
				{
					// 按标准文件目录查询数据元
					Method:  http.MethodGet,
					Path:    "/query/byStdFileCatalog",
					Handler: dataelement.QueryByStdFileCatalogHandler(serverCtx),
				},
				{
					// 检查名称重复
					Method:  http.MethodGet,
					Path:    "/query/isRepeat",
					Handler: dataelement.IsRepeatHandler(serverCtx),
				},
				{
					// 查询数据元关联的标准文件
					Method:  http.MethodGet,
					Path:    "/query/stdFile/:id",
					Handler: dataelement.QueryStdFileHandler(serverCtx),
				},
				{
					// 启用/停用数据元
					Method:  http.MethodPut,
					Path:    "/state/:ids",
					Handler: dataelement.UpdateStateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/v1/dataelement"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 内部查看数据元详情
				Method:  http.MethodGet,
				Path:    "/internal/get/:id",
				Handler: dataelement.GetDataElementInternalHandler(serverCtx),
			},
			{
				// 按规则ID分页查询数据元
				Method:  http.MethodPost,
				Path:    "/internal/getDataElementPageByRuleId",
				Handler: dataelement.GetPageByRuleIdHandler(serverCtx),
			},
			{
				// 内部分页查询数据元
				Method:  http.MethodGet,
				Path:    "/internal/list",
				Handler: dataelement.ListDataElementInternalHandler(serverCtx),
			},
			{
				// 内部批量查询数据元
				Method:  http.MethodPost,
				Path:    "/internal/queryByIds",
				Handler: dataelement.QueryByIdsInternalHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/dataelement"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenCheck},
			[]rest.Route{
				{
					// 新增码表
					Method:  http.MethodPost,
					Path:    "/dict",
					Handler: dict.CreateDictHandler(serverCtx),
				},
				{
					// 码表列表查询
					Method:  http.MethodGet,
					Path:    "/dict",
					Handler: dict.ListDictHandler(serverCtx),
				},
				{
					// 修改码表
					Method:  http.MethodPut,
					Path:    "/dict/:id",
					Handler: dict.UpdateDictHandler(serverCtx),
				},
				{
					// 码表详情（按ID）
					Method:  http.MethodGet,
					Path:    "/dict/:id",
					Handler: dict.GetDictHandler(serverCtx),
				},
				{
					// 码表详情（按Code）
					Method:  http.MethodGet,
					Path:    "/dict/code/:code",
					Handler: dict.GetDictByCodeHandler(serverCtx),
				},
				{
					// 启用/停用码表
					Method:  http.MethodPut,
					Path:    "/dict/state/:id",
					Handler: dict.UpdateDictStateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/standardization/v1/dataelement"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 删除码表
				Method:  http.MethodDelete,
				Path:    "/dict/:id",
				Handler: dict.DeleteDictHandler(serverCtx),
			},
			{
				// 批量删除码表
				Method:  http.MethodDelete,
				Path:    "/dict/batch/:ids",
				Handler: dict.BatchDeleteDictHandler(serverCtx),
			},
			{
				// 查询引用码表的数据元
				Method:  http.MethodGet,
				Path:    "/dict/dataelement/:id",
				Handler: dict.QueryDictByDataElementHandler(serverCtx),
			},
			{
				// 码值分页查询
				Method:  http.MethodGet,
				Path:    "/dict/enum",
				Handler: dict.ListDictEnumHandler(serverCtx),
			},
			{
				// 码值列表查询（不分页）
				Method:  http.MethodGet,
				Path:    "/dict/enum/getList",
				Handler: dict.GetDictEnumListHandler(serverCtx),
			},
			{
				// 按文件查询码表
				Method:  http.MethodGet,
				Path:    "/dict/queryByStdFile",
				Handler: dict.QueryDictByStdFileHandler(serverCtx),
			},
			{
				// 按文件目录查询码表
				Method:  http.MethodGet,
				Path:    "/dict/queryByStdFileCatalog",
				Handler: dict.QueryDictByStdFileCatalogHandler(serverCtx),
			},
			{
				// 查询数据是否存在
				Method:  http.MethodGet,
				Path:    "/dict/queryDataExists",
				Handler: dict.QueryDictDataExistsHandler(serverCtx),
			},
			{
				// 添加关联关系
				Method:  http.MethodPut,
				Path:    "/dict/relation/:id",
				Handler: dict.AddDictRelationHandler(serverCtx),
			},
			{
				// 查询关联标准文件
				Method:  http.MethodGet,
				Path:    "/dict/relation/stdfile/:id",
				Handler: dict.QueryDictRelationStdfileHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/standardization/v1/dataelement"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 新增编码规则
				Method:  http.MethodPost,
				Path:    "/rule",
				Handler: rule.CreateRuleHandler(serverCtx),
			},
			{
				// 编码规则列表查询
				Method:  http.MethodGet,
				Path:    "/rule",
				Handler: rule.ListRuleHandler(serverCtx),
			},
			{
				// 根据ID修改编码规则
				Method:  http.MethodPut,
				Path:    "/rule/:id",
				Handler: rule.UpdateRuleHandler(serverCtx),
			},
			{
				// 编码规则详情查看
				Method:  http.MethodGet,
				Path:    "/rule/:id",
				Handler: rule.GetRuleHandler(serverCtx),
			},
			{
				// 编码规则删除&批量删除
				Method:  http.MethodDelete,
				Path:    "/rule/:ids",
				Handler: rule.DeleteRuleHandler(serverCtx),
			},
			{
				// 编码规则目录移动
				Method:  http.MethodPost,
				Path:    "/rule/catalog/remove",
				Handler: rule.RemoveRuleCatalogHandler(serverCtx),
			},
			{
				// 获取自定义日期格式列表
				Method:  http.MethodGet,
				Path:    "/rule/getCustomDateFormat",
				Handler: rule.GetCustomDateFormatHandler(serverCtx),
			},
			{
				// 批量查询规则
				Method:  http.MethodPost,
				Path:    "/rule/queryByIds",
				Handler: rule.QueryRuleByIdsHandler(serverCtx),
			},
			{
				// 根据标准文件查询规则
				Method:  http.MethodGet,
				Path:    "/rule/queryByStdFile",
				Handler: rule.QueryRuleByStdFileHandler(serverCtx),
			},
			{
				// 根据标准文件目录查询规则
				Method:  http.MethodGet,
				Path:    "/rule/queryByStdFileCatalog",
				Handler: rule.QueryRuleByStdFileCatalogHandler(serverCtx),
			},
			{
				// 检查数据是否存在
				Method:  http.MethodGet,
				Path:    "/rule/queryDataExists",
				Handler: rule.QueryDataExistsHandler(serverCtx),
			},
			{
				// 查询引用规则的数据元
				Method:  http.MethodGet,
				Path:    "/rule/relation/de/:id",
				Handler: rule.QueryRuleUsedDataElementHandler(serverCtx),
			},
			{
				// 查询规则关联的标准文件
				Method:  http.MethodGet,
				Path:    "/rule/relation/stdfile/:id",
				Handler: rule.QueryStdFilesByRuleHandler(serverCtx),
			},
			{
				// 停用/启用编码规则
				Method:  http.MethodPut,
				Path:    "/rule/state/:id",
				Handler: rule.UpdateRuleStateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/standardization/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 内部-根据数据元编码查看规则详情
				Method:  http.MethodGet,
				Path:    "/getDetailByDataCode/:dataCode",
				Handler: rule.GetRuleDetailByDataCodeHandler(serverCtx),
			},
			{
				// 内部-根据数据元ID查看规则详情
				Method:  http.MethodGet,
				Path:    "/getDetailByDataId/:dataId",
				Handler: rule.GetRuleDetailByDataIdHandler(serverCtx),
			},
			{
				// 内部-根据ID查看规则详情
				Method:  http.MethodGet,
				Path:    "/getId/:id",
				Handler: rule.GetRuleInternalHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/standardization/v1/rule/internal"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenCheck},
			[]rest.Route{
				{
					// 新增标准文件
					Method:  http.MethodPost,
					Path:    "/std-file",
					Handler: stdfile.CreateStdFileHandler(serverCtx),
				},
				{
					// 标准文件-列表查询
					Method:  http.MethodGet,
					Path:    "/std-file",
					Handler: stdfile.ListStdFileHandler(serverCtx),
				},
				{
					// 根据ID修改标准文件
					Method:  http.MethodPut,
					Path:    "/std-file/:id",
					Handler: stdfile.UpdateStdFileHandler(serverCtx),
				},
				{
					// 根据ID查询详情
					Method:  http.MethodGet,
					Path:    "/std-file/:id",
					Handler: stdfile.GetStdFileHandler(serverCtx),
				},
				{
					// 根据id列表查询
					Method:  http.MethodPost,
					Path:    "/std-file/queryByIds",
					Handler: stdfile.QueryStdFileByIdsHandler(serverCtx),
				},
				{
					// 根据文件ID启用/停用
					Method:  http.MethodPut,
					Path:    "/std-file/state/:id",
					Handler: stdfile.UpdateStdFileStateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/standardization/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 批量启用/停用
				Method:  http.MethodPut,
				Path:    "/std-file/batchState",
				Handler: stdfile.BatchStateStdFileHandler(serverCtx),
			},
			{
				// 移动到指定目录-目录移动
				Method:  http.MethodPost,
				Path:    "/std-file/catalog/remove",
				Handler: stdfile.RemoveStdFileCatalogHandler(serverCtx),
			},
			{
				// 标准文件管理-批量删除
				Method:  http.MethodDelete,
				Path:    "/std-file/delete/:ids",
				Handler: stdfile.DeleteStdFileHandler(serverCtx),
			},
			{
				// 根据文件ID下载标准文件附件
				Method:  http.MethodGet,
				Path:    "/std-file/download/:id",
				Handler: stdfile.DownloadStdFileHandler(serverCtx),
			},
			{
				// 标准文件附件下载（批量）
				Method:  http.MethodPost,
				Path:    "/std-file/downloadBatch",
				Handler: stdfile.DownloadBatchStdFileHandler(serverCtx),
			},
			{
				// 查询数据是否存在
				Method:  http.MethodGet,
				Path:    "/std-file/queryDataExists",
				Handler: stdfile.QueryDataExistsHandler(serverCtx),
			},
			{
				// 根据标准文件ID添加关联关系
				Method:  http.MethodPut,
				Path:    "/std-file/relation/:id",
				Handler: stdfile.AddRelationHandler(serverCtx),
			},
			{
				// 标准文件关联关系查询
				Method:  http.MethodGet,
				Path:    "/std-file/relation/:id",
				Handler: stdfile.QueryRelationsHandler(serverCtx),
			},
			{
				// 查询关联数据元
				Method:  http.MethodGet,
				Path:    "/std-file/relation/de/:id",
				Handler: stdfile.QueryRelationDeHandler(serverCtx),
			},
			{
				// 查询关联的码表
				Method:  http.MethodGet,
				Path:    "/std-file/relation/dict/:id",
				Handler: stdfile.QueryRelationDictHandler(serverCtx),
			},
			{
				// 查询关联编码规则
				Method:  http.MethodGet,
				Path:    "/std-file/relation/rule/:id",
				Handler: stdfile.QueryRelationRuleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/standardization/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenCheck},
			[]rest.Route{
				{
					// 采纳
					Method:  http.MethodPut,
					Path:    "/accept",
					Handler: task.AcceptHandler(serverCtx),
				},
				{
					// 添加至待新建
					Method:  http.MethodPost,
					Path:    "/addToPending",
					Handler: task.AddToPendingHandler(serverCtx),
				},
				{
					// 撤销
					Method:  http.MethodPut,
					Path:    "/cancelBusinessTableField",
					Handler: task.CancelFieldHandler(serverCtx),
				},
				{
					// 新建标准任务
					Method:  http.MethodPost,
					Path:    "/createTask",
					Handler: task.CreateTaskHandler(serverCtx),
				},
				{
					// 移除字段
					Method:  http.MethodDelete,
					Path:    "/deleteBusinessTableField/:id",
					Handler: task.DeleteFieldHandler(serverCtx),
				},
				{
					// 完成任务
					Method:  http.MethodPost,
					Path:    "/finishTask/:task_id",
					Handler: task.FinishTaskHandler(serverCtx),
				},
				{
					// 业务表列表
					Method:  http.MethodGet,
					Path:    "/getBusinessTable",
					Handler: task.GetBusinessTableHandler(serverCtx),
				},
				{
					// 业务表字段列表
					Method:  http.MethodGet,
					Path:    "/getBusinessTableField",
					Handler: task.GetBusinessTableFieldHandler(serverCtx),
				},
				{
					// 任务关联字段
					Method:  http.MethodGet,
					Path:    "/getBusinessTableFieldFromTask",
					Handler: task.GetFieldFromTaskHandler(serverCtx),
				},
				{
					// 任务关联业务表
					Method:  http.MethodGet,
					Path:    "/getBusinessTableFromTask",
					Handler: task.GetTableFromTaskHandler(serverCtx),
				},
				{
					// 进度查询
					Method:  http.MethodPost,
					Path:    "/queryTaskProcess",
					Handler: task.QueryTaskProcessHandler(serverCtx),
				},
				{
					// 任务状态查询
					Method:  http.MethodPost,
					Path:    "/queryTaskState",
					Handler: task.QueryTaskStateHandler(serverCtx),
				},
				{
					// 编码规则推荐
					Method:  http.MethodPost,
					Path:    "/rule-rec/rec",
					Handler: task.RuleRecHandler(serverCtx),
				},
				{
					// 标准推荐（弹框）
					Method:  http.MethodPost,
					Path:    "/stand-rec/rec",
					Handler: task.StandRecHandler(serverCtx),
				},
				{
					// 标准创建（内部）
					Method:  http.MethodPost,
					Path:    "/std-create",
					Handler: task.StdCreateHandler(serverCtx),
				},
				{
					// 已完成任务列表
					Method:  http.MethodGet,
					Path:    "/std-create/completed",
					Handler: task.GetCompletedTasksHandler(serverCtx),
				},
				{
					// 任务详情
					Method:  http.MethodGet,
					Path:    "/std-create/completed/:id",
					Handler: task.GetTaskByIdHandler(serverCtx),
				},
				{
					// 标准关联提交
					Method:  http.MethodPost,
					Path:    "/std-create/publish/submit",
					Handler: task.SubmitRelationHandler(serverCtx),
				},
				{
					// 标准关联暂存
					Method:  http.MethodPost,
					Path:    "/std-create/relation/staging",
					Handler: task.StagingRelationHandler(serverCtx),
				},
				{
					// 未处理任务列表
					Method:  http.MethodGet,
					Path:    "/std-create/uncompleted",
					Handler: task.GetUncompletedTasksHandler(serverCtx),
				},
				{
					// 标准推荐（内部）
					Method:  http.MethodPost,
					Path:    "/std-rec/rec",
					Handler: task.StdRecHandler(serverCtx),
				},
				{
					// 提交选定数据元
					Method:  http.MethodPost,
					Path:    "/submitDataElement",
					Handler: task.SubmitDataElementHandler(serverCtx),
				},
				{
					// 修改字段说明
					Method:  http.MethodPut,
					Path:    "/updateDescription",
					Handler: task.UpdateDescriptionHandler(serverCtx),
				},
				{
					// 修改表名称
					Method:  http.MethodPut,
					Path:    "/updateTableName",
					Handler: task.UpdateTableNameHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/standardization/v1/dataelement/task"),
	)
}
