// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	stdfile "github.com/kweaver-ai/dsg/services/apps/standardization-backend/api/internal/handler/stdfile"
	"github.com/kweaver-ai/dsg/services/apps/standardization-backend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenCheck},
			[]rest.Route{
				{
					// 新增标准文件
					Method:  http.MethodPost,
					Path:    "/std-file",
					Handler: stdfile.CreateStdFileHandler(serverCtx),
				},
				{
					// 标准文件-列表查询
					Method:  http.MethodGet,
					Path:    "/std-file",
					Handler: stdfile.ListStdFileHandler(serverCtx),
				},
				{
					// 根据ID修改标准文件
					Method:  http.MethodPut,
					Path:    "/std-file/:id",
					Handler: stdfile.UpdateStdFileHandler(serverCtx),
				},
				{
					// 根据ID查询详情
					Method:  http.MethodGet,
					Path:    "/std-file/:id",
					Handler: stdfile.GetStdFileHandler(serverCtx),
				},
				{
					// 根据id列表查询
					Method:  http.MethodPost,
					Path:    "/std-file/queryByIds",
					Handler: stdfile.QueryStdFileByIdsHandler(serverCtx),
				},
				{
					// 根据文件ID启用/停用
					Method:  http.MethodPut,
					Path:    "/std-file/state/:id",
					Handler: stdfile.UpdateStdFileStateHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/standardization/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 批量启用/停用
				Method:  http.MethodPut,
				Path:    "/std-file/batchState",
				Handler: stdfile.BatchStateStdFileHandler(serverCtx),
			},
			{
				// 移动到指定目录-目录移动
				Method:  http.MethodPost,
				Path:    "/std-file/catalog/remove",
				Handler: stdfile.RemoveStdFileCatalogHandler(serverCtx),
			},
			{
				// 标准文件管理-批量删除
				Method:  http.MethodDelete,
				Path:    "/std-file/delete/:ids",
				Handler: stdfile.DeleteStdFileHandler(serverCtx),
			},
			{
				// 根据文件ID下载标准文件附件
				Method:  http.MethodGet,
				Path:    "/std-file/download/:id",
				Handler: stdfile.DownloadStdFileHandler(serverCtx),
			},
			{
				// 标准文件附件下载（批量）
				Method:  http.MethodPost,
				Path:    "/std-file/downloadBatch",
				Handler: stdfile.DownloadBatchStdFileHandler(serverCtx),
			},
			{
				// 查询数据是否存在
				Method:  http.MethodGet,
				Path:    "/std-file/queryDataExists",
				Handler: stdfile.QueryDataExistsHandler(serverCtx),
			},
			{
				// 根据标准文件ID添加关联关系
				Method:  http.MethodPut,
				Path:    "/std-file/relation/:id",
				Handler: stdfile.AddRelationHandler(serverCtx),
			},
			{
				// 标准文件关联关系查询
				Method:  http.MethodGet,
				Path:    "/std-file/relation/:id",
				Handler: stdfile.QueryRelationsHandler(serverCtx),
			},
			{
				// 查询关联数据元
				Method:  http.MethodGet,
				Path:    "/std-file/relation/de/:id",
				Handler: stdfile.QueryRelationDeHandler(serverCtx),
			},
			{
				// 查询关联的码表
				Method:  http.MethodGet,
				Path:    "/std-file/relation/dict/:id",
				Handler: stdfile.QueryRelationDictHandler(serverCtx),
			},
			{
				// 查询关联编码规则
				Method:  http.MethodGet,
				Path:    "/std-file/relation/rule/:id",
				Handler: stdfile.QueryRelationRuleHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/standardization/v1"),
	)
}
