// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	catalog "github.com/tianyuliang/standardization-backend/api/internal/handler/catalog"
	"github.com/tianyuliang/standardization-backend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthCheckHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Validator},
			[]rest.Route{
				{
					// 创建目录
					Method:  http.MethodPost,
					Path:    "/",
					Handler: catalog.CreateHandler(serverCtx),
				},
				{
					// 修改目录
					Method:  http.MethodPut,
					Path:    "/:id",
					Handler: catalog.UpdateHandler(serverCtx),
				},
				{
					// 删除目录
					Method:  http.MethodDelete,
					Path:    "/:id",
					Handler: catalog.DeleteHandler(serverCtx),
				},
				{
					// 按名称检索目录
					Method:  http.MethodGet,
					Path:    "/query",
					Handler: catalog.QueryHandler(serverCtx),
				},
				{
					// 查询目录与文件树列表
					Method:  http.MethodGet,
					Path:    "/query/with_file",
					Handler: catalog.QuerywithfileHandler(serverCtx),
				},
				{
					// 查询目录树
					Method:  http.MethodGet,
					Path:    "/query_tree",
					Handler: catalog.QuerytreeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/catalog"),
	)
}
