-- {{feature_name}} DDL
-- Generated by Spec Kit | IDRM Project
-- Location: migrations/{module}/raw/{table}.sql

CREATE TABLE `{{table_name}}` (
    `id` CHAR(36) NOT NULL COMMENT '主键ID (UUID v7)',
    -- === Business Fields ===
    -- `name` varchar(100) NOT NULL COMMENT '名称',
    -- `code` varchar(50) NOT NULL COMMENT '编码',
    -- `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态: 1-启用, 0-禁用',
    
    -- === Audit Fields ===
    `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
    `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
    `deleted_at` datetime(3) DEFAULT NULL COMMENT '删除时间(软删除)',
    
    PRIMARY KEY (`id`)
    -- ⚠️ 注意: 唯一索引必须包含 deleted_at 以支持软删除
    -- UNIQUE KEY `uk_code` (`code`, `deleted_at`),
    -- KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='{{table_comment}}';
