// Code generated by speckit. DO NOT EDIT.
// Package errorx provides task-specific error codes and handlers.

package errorx

import (
	"github.com/jinguoxing/idrm-go-base/errorx"
)

const (
	// ErrCodeTaskDataNotExist 数据不存在
	ErrCodeTaskDataNotExist = 30701
	// ErrCodeTaskParamEmpty 参数为空
	ErrCodeTaskParamEmpty = 30702
	// ErrCodeTaskInvalidParam 参数无效
	ErrCodeTaskInvalidParam = 30703
	// ErrCodeTaskBusinessTableNotExist 业务表不存在
	ErrCodeTaskBusinessTableNotExist = 30704
	// ErrCodeTaskNotExist 任务不存在
	ErrCodeTaskNotExist = 30705
)

// TaskDataNotExist 数据不存在
func TaskDataNotExist() error {
	return errorx.NewWithMsg(ErrCodeTaskDataNotExist, "Data not exist")
}

// TaskParamEmpty 参数为空
func TaskParamEmpty(field string) error {
	return errorx.NewWithMsg(ErrCodeTaskParamEmpty, field+" cannot be empty")
}

// TaskInvalidParam 参数无效
func TaskInvalidParam(field string) error {
	return errorx.NewWithMsg(ErrCodeTaskInvalidParam, field+" is invalid")
}

// TaskBusinessTableNotExist 业务表不存在
func TaskBusinessTableNotExist() error {
	return errorx.NewWithMsg(ErrCodeTaskBusinessTableNotExist, "Business table does not exist")
}

// TaskNotExist 任务不存在
func TaskNotExist() error {
	return errorx.NewWithMsg(ErrCodeTaskNotExist, "Task does not exist")
}
