openapi: 3.0.0
info:
  title: 标准文件管理 API
  version: 1.0.0
  description: 从 Java 迁移的标准文件管理接口，16个API端点

servers:
  - url: /api/standardization/v1
    description: 外部API基路径

tags:
  - name: open
    description: 外部可访问的API
  - name: internal
    description: 内部或无需认证的API

paths:
  /std-file:
    post:
      tags: [open]
      summary: 新增标准文件
      operationId: createStdFile
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateStdFileReq'
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StdFileResp'

    put:
      tags: [open]
      summary: 根据ID修改标准文件
      operationId: updateStdFile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/UpdateStdFileReq'
      responses:
        '200':
          description: 修改成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StdFileResp'

    get:
      tags: [open]
      summary: 标准文件-列表查询
      operationId: listStdFile
      parameters:
        - $ref: '#/components/parameters/CatalogId'
        - $ref: '#/components/parameters/Keyword'
        - $ref: '#/components/parameters/OrgType'
        - $ref: '#/components/parameters/State'
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Limit'
        - $ref: '#/components/parameters/Sort'
        - $ref: '#/components/parameters/Direction'
        - $ref: '#/components/parameters/DepartmentId'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StdFileListResp'

  /std-file/{id}:
    get:
      tags: [open]
      summary: 根据ID查询详情
      operationId: getStdFile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StdFileResp'

  /std-file/delete/{ids}:
    delete:
      tags: [internal]
      summary: 标准文件管理-批量删除
      operationId: deleteStdFile
      parameters:
        - name: ids
          in: path
          required: true
          schema:
            type: string
          description: 多个ID用逗号分隔
      responses:
        '200':
          description: 删除成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResp'

  /std-file/state/{id}:
    put:
      tags: [open]
      summary: 根据文件ID启用/停用
      operationId: updateStdFileState
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStdFileStateReq'
      responses:
        '200':
          description: 状态更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResp'

  /std-file/catalog/remove:
    post:
      tags: [internal]
      summary: 移动到指定目录-目录移动
      operationId: removeStdFileCatalog
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveCatalogReq'
      responses:
        '200':
          description: 移动成功
          content:
            application/json:
              schema:
                type: integer
                description: 更新的记录数

  /std-file/download/{id}:
    get:
      tags: [internal]
      summary: 根据文件ID下载标准文件附件
      operationId: downloadStdFile
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 下载成功
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  /std-file/downloadBatch:
    post:
      tags: [internal]
      summary: 标准文件附件下载（批量）
      operationId: downloadBatchStdFile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryByIdsReq'
      responses:
        '200':
          description: 下载成功
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                description: ZIP压缩包

  /std-file/relation/de/{id}:
    get:
      tags: [open]
      summary: 查询关联数据元
      operationId: queryRelationDe
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Limit'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  description:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/DataElementResp'
                  totalCount:
                    type: integer

  /std-file/relation/dict/{id}:
    get:
      tags: [open]
      summary: 查询关联的码表
      operationId: queryRelationDict
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Limit'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  description:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/DictResp'
                  totalCount:
                    type: integer

  /std-file/relation/rule/{id}:
    get:
      tags: [open]
      summary: 查询关联编码规则
      operationId: queryRelationRule
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - $ref: '#/components/parameters/Offset'
        - $ref: '#/components/parameters/Limit'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  description:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/RuleResp'
                  totalCount:
                    type: integer

  /std-file/relation/{id}:
    put:
      tags: [open]
      summary: 根据标准文件ID添加与数据元&码表&编码规则的关联
      operationId: addRelation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StdFileRelationDto'
      responses:
        '200':
          description: 添加成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResp'

    get:
      tags: [open]
      summary: 标准文件关联关系查询
      operationId: queryRelations
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                  description:
                    type: string
                  data:
                    $ref: '#/components/schemas/StdFileRelationResp'

  /std-file/queryDataExists:
    get:
      tags: [internal]
      summary: 查询数据是否存在
      operationId: queryDataExists
      parameters:
        - name: number
          in: query
          schema:
            type: string
        - name: org_type
          in: query
          schema:
            type: integer
        - name: name
          in: query
          schema:
            type: string
        - name: filter_id
          in: query
          schema:
            type: integer
            format: int64
        - name: department_ids
          in: query
          schema:
            type: string
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/BaseResp'
                  - type: object
                    properties:
                      data:
                        type: boolean

  /std-file/queryByIds:
    post:
      tags: [open]
      summary: 根据id集合查询列表
      operationId: queryStdFileByIds
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryByIdsReq'
      responses:
        '200':
          description: 查询成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StdFileListResp'

  /std-file/batchState:
    put:
      tags: [internal]
      summary: 批量启用/停用
      operationId: batchStateStdFile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchStateReq'
      responses:
        '200':
          description: 批量更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaseResp'

components:
  parameters:
    CatalogId:
      name: catalog_id
      in: query
      schema:
        type: integer
        format: int64
        default: 44
      description: 目录ID

    Keyword:
      name: keyword
      in: query
      schema:
        type: string
      description: 搜索关键字

    OrgType:
      name: org_type
      in: query
      schema:
        type: integer
        enum: [0, 1, 2, 3, 4, 5, 6, 99]
      description: 标准分类

    State:
      name: state
      in: query
      schema:
        type: string
        enum: [enable, disable]
      description: 启用停用

    Offset:
      name: offset
      in: query
      schema:
        type: integer
        default: 1
      description: 分页页码

    Limit:
      name: limit
      in: query
      schema:
        type: integer
        default: 20
      description: 条数

    Sort:
      name: sort
      in: query
      schema:
        type: string
        default: update_time
      description: 排序字段

    Direction:
      name: direction
      in: query
      schema:
        type: string
        enum: [asc, desc]
        default: desc
      description: 排序方向

    DepartmentId:
      name: department_id
      in: query
      schema:
        type: string
      description: 部门ID

  schemas:
    CreateStdFileReq:
      type: object
      required:
        - name
        - org_type
        - attachment_type
      properties:
        number:
          type: string
          maxLength: 300
          description: 标准编号
        name:
          type: string
          maxLength: 300
          description: 标准文件名称
        catalog_id:
          type: integer
          format: int64
          default: 44
          description: 目录ID
        org_type:
          type: integer
          enum: [0, 1, 2, 3, 4, 5, 6, 99]
          description: 标准分类
        act_date:
          type: string
          format: date
          description: 实施日期
        publish_date:
          type: string
          format: date
          description: 发布日期
        description:
          type: string
          maxLength: 300
          description: 说明
        attachment_type:
          type: string
          enum: [FILE, URL]
          description: 附件类型
        attachment_url:
          type: string
          maxLength: 500
          description: 链接地址
        state:
          type: string
          enum: [enable, disable]
          description: 启用停用
        department_ids:
          type: string
          description: 部门ID

    UpdateStdFileReq:
      type: object
      required:
        - name
        - catalog_id
        - org_type
        - attachment_type
      properties:
        number:
          type: string
          maxLength: 300
        name:
          type: string
          maxLength: 300
        catalog_id:
          type: integer
          format: int64
        org_type:
          type: integer
          enum: [0, 1, 2, 3, 4, 5, 6, 99]
        act_date:
          type: string
          format: date
        publish_date:
          type: string
          format: date
        description:
          type: string
          maxLength: 300
        attachment_type:
          type: string
          enum: [FILE, URL]
        attachment_url:
          type: string
          maxLength: 500
        state:
          type: string
          enum: [enable, disable]
        department_ids:
          type: string

    UpdateStdFileStateReq:
      type: object
      required:
        - state
      properties:
        state:
          type: string
          enum: [enable, disable]
        reason:
          type: string
          maxLength: 800
          description: 停用原因（state=disable时必填）

    RemoveCatalogReq:
      type: object
      required:
        - ids
        - catalogId
      properties:
        ids:
          type: array
          items:
            type: integer
            format: int64
        catalogId:
          type: integer
          format: int64

    BatchStateReq:
      type: object
      required:
        - ids
        - state
      properties:
        ids:
          type: array
          items:
            type: integer
            format: int64
        state:
          type: string
          enum: [enable, disable]
        reason:
          type: string
          maxLength: 800

    QueryByIdsReq:
      type: object
      required:
        - ids
      properties:
        ids:
          type: array
          items:
            type: integer
            format: int64

    StdFileRelationDto:
      type: object
      properties:
        deIds:
          type: array
          items:
            type: integer
            format: int64
        dictIds:
          type: array
          items:
            type: integer
            format: int64
        ruleIds:
          type: array
          items:
            type: integer
            format: int64

    StdFileResp:
      type: object
      properties:
        id:
          type: integer
          format: int64
        number:
          type: string
        name:
          type: string
        catalogId:
          type: integer
          format: int64
        catalogName:
          type: string
        actDate:
          type: string
          format: date
        publishDate:
          type: string
          format: date
        disableDate:
          type: string
          format: date
        attachmentType:
          type: string
          enum: [FILE, URL]
        attachmentUrl:
          type: string
        fileName:
          type: string
        orgType:
          type: integer
          enum: [0, 1, 2, 3, 4, 5, 6, 99]
        description:
          type: string
        state:
          type: string
          enum: [enable, disable]
        disableReason:
          type: string
        version:
          type: integer
        departmentId:
          type: string
        departmentName:
          type: string
        departmentPathNames:
          type: string
        createTime:
          type: string
          format: date-time
        createUser:
          type: string
        updateTime:
          type: string
          format: date-time
        updateUser:
          type: string

    StdFileListResp:
      type: object
      properties:
        code:
          type: string
        description:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/StdFileResp'
        totalCount:
          type: integer
          format: int64

    StdFileRelationResp:
      type: object
      properties:
        deIds:
          type: array
          items:
            type: integer
            format: int64
        dictIds:
          type: array
          items:
            type: integer
            format: int64
        ruleIds:
          type: array
          items:
            type: integer
            format: int64

    BaseResp:
      type: object
      properties:
        code:
          type: string
        description:
          type: string

    DataElementResp:
      type: object
      properties:
        id:
          type: integer
          format: int64
        dataCode:
          type: string
        dataName:
          type: string

    DictResp:
      type: object
      properties:
        id:
          type: integer
          format: int64
        dictCode:
          type: string
        dictName:
          type: string

    RuleResp:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        ruleType:
          type: string
          enum: [REGEX, CUSTOM]
