-- 数据元基本信息表
CREATE TABLE `t_data_element_info` (
  `f_id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `f_de_id` bigint(20) NOT NULL COMMENT '关联标识',
  `f_name_en` varchar(128) NOT NULL COMMENT '英文名称',
  `f_name_cn` varchar(128) NOT NULL COMMENT '中文名称',
  `f_synonym` varchar(300) DEFAULT NULL COMMENT '同义词',
  `f_std_type` INT(2) NOT NULL COMMENT '标准分类',
  `f_data_type` INT(2) NOT NULL COMMENT '数据类型',
  `f_data_length` INT(4) DEFAULT NULL COMMENT '数据长度',
  `f_data_precision` INT(4) DEFAULT NULL COMMENT '数据精度',
  `f_dict_code` bigint(20) DEFAULT NULL COMMENT '关联码表编码',
  `f_rule_id` bigint(20) DEFAULT NULL COMMENT '关联编码规则ID',
  `f_relation_type` VARCHAR(50) DEFAULT 'no' COMMENT '关联类型：no/codeTable/codeRule',
  `f_catalog_id` bigint(20) NOT NULL COMMENT '目录ID',
  `f_label_id` bigint(20) DEFAULT NULL COMMENT '数据分级标签ID',
  `f_description` varchar(300) DEFAULT NULL COMMENT '说明',
  `f_version` INT(4) NOT NULL DEFAULT 1 COMMENT '版本号',
  `f_state` INT(2) NOT NULL DEFAULT 1 COMMENT '状态：1-启用，0-停用',
  `f_authority_id` varchar(100) DEFAULT NULL COMMENT '权限域',
  `f_department_ids` varchar(350) DEFAULT NULL COMMENT '部门ID',
  `f_third_dept_id` varchar(36) DEFAULT NULL COMMENT '第三方部门ID',
  `f_disable_reason` varchar(800) DEFAULT NULL COMMENT '停用原因',
  `f_create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `f_create_user` varchar(128) DEFAULT NULL COMMENT '创建用户',
  `f_update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `f_update_user` varchar(128) DEFAULT NULL COMMENT '修改用户',
  `f_deleted` bigint(20) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  PRIMARY KEY (`f_id`),
  UNIQUE KEY `uk_de_id` (`f_de_id`),
  KEY `idx_dict_code` (`f_dict_code`),
  KEY `idx_rule_id` (`f_rule_id`),
  KEY `idx_catalog_id` (`f_catalog_id`),
  KEY `idx_state` (`f_state`),
  KEY `idx_std_type` (`f_std_type`),
  KEY `idx_deleted` (`f_deleted`),
  KEY `idx_name_cn_std_type` (`f_name_cn`, `f_std_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据元基本信息表';
